-- SELECT TO_NUMBER(DATETIME) "HOUR", COUNT(*) COUNT , DATETIME
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR
-- HAVING HOUR >= 9 and HOUR <=19
-- ORDER BY HOUR

SELECT TO_NUMBER(DATETIME),
        COUNT(*) "COUNT"
FROM(
SELECT TO_CHAR(DATETIME, 'HH24') "DATETIME"
FROM ANIMAL_OUTS
)
WHERE DATETIME > 8 AND DATETIME<20
GROUP BY DATETIME
ORDER BY DATETIME